SELECT 
    PLAYER_ID, 
    REPLACE(REPLACE(PLAYER_ID, 'xuid(', ''), ')', '') AS XUID_NUMERIC, 
    '' AS GAMERTAG
FROM 
    GRUNT_STAGING.MATCH_DET_PLAYERS
WHERE 
    LENGTH(PLAYER_ID) > 9
    AND PLAYER_ID NOT IN 
        (SELECT PLAYER_ID FROM GRUNT_STAGING.PLAYERS)
GROUP BY 
    PLAYER_ID
ORDER BY 
    COUNT(*) DESC;